pipelines:
  wmf-publish:
    stages:
      - name: wikiversions
        build: list-wikiversions
        run:
          tail: 10
        blubberfile: &blubberfile
          version: v4
          apt:
            proxies: ['${setup.httpProxy}']
          variants:
            list-wikiversions:
              base: docker-registry.wikimedia.org/php7.2-cli
              builder:
                requirements: [wikiversions.json, multiversion/]
                command: [bash, -c, 'multiversion/bin/list-versions.php | cut -f 2 > versions']
              entrypoint: [cat, versions]
            rsync:
              base: docker-registry.wikimedia.org/wikimedia-buster
              apt:
                packages: [rsync]
              entrypoint: [rsync]
      - name: fetch-private
        build: rsync
        run:
          arguments: [-a, 'deployment.eqiad.wmnet::srv-mediawiki-private-primary/', /tmp/private/]
        copy:
          - source: /tmp/private/
            destination: private
        blubberfile: *blubberfile
      - name: fetch-patches
        build: rsync
        run:
          arguments: [-a, 'deployment.eqiad.wmnet::srv-patches-releases-primary/', /tmp/patches/]
        copy:
          - source: /tmp/patches
            destination: patches
        blubberfile: *blubberfile
      - name: production
        build:
          variant: production
          excludes:
            - .git
        publish:
          image:
            name: mediawiki-multiversion
            tags: [production]
        blubberfile:
          version: v4
          apt:
            proxies: ['${setup.httpProxy}']
          variants:
            production:
              base: docker-registry.wikimedia.org/php7.2-fpm
              apt:
                packages:
                  - firejail
                  - patch
              lives:
                in: /srv/mediawiki
              runs:
                # match base image www-data uid/gid
                uid: 33
                gid: 33
              builder:
                requirements:
                  $merge:
                    $each: version
                    $in: "${wikiversions.output}"
                    $yield:
                      from: "docker-registry.wikimedia.org/wikimedia/mediawiki:wmf-${.version}"
                      source: /srv/mediawiki
                      destination: "/srv/mediawiki/php-${.version}"
                  $with:
                    - .
                command: [./.pipeline/wmf-publish/build]
      - name: webserver
        build:
          variant: production
          excludes:
            - .git
            - wmf-config
            - tests
            - php
            - src
            - multiversion
        publish:
          image:
            name: mediawiki-webserver
            tags: ["production"]
        blubberfile:
          version: v4
          runs:
            uid: 33
            gid: 33
          variants:
            production:
              base: docker-registry.wikimedia.org/mediawiki-httpd
              copies: [local]
              lives:
                in: /srv/mediawiki
