# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Wikimedia Api Portal Wiki.
# See the inheritance tree to find where most settings are defined.

# FIXME: This is currently Beta-Cluster only and maybe we should define Beta Cluster's needs distinctly?

inheritsFrom:
  - special
  - all-labs
  - nowikidatadescriptiontaglines
  - s5
  - small
  - group0
