# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Czech Wikipedia Arbitration Committee.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - nowikidatadescriptiontaglines
  - pp_stage1
  - private
  - s3
  - securepollglobal
  - small
  - wikipedia-english
