# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Dutch Wikipedia Arbitration Committee.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - nowikidatadescriptiontaglines
  - private
  - s3
  - securepollglobal
  - small
  - visualeditor-nondefault
