# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Aramaic Wikipedia.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - categories-rdf
  - commonsuploads
  # To be removed by end of 2020
  - mobilemainpagelegacy
  - pp_stage1
  - rtl
  - s3
  - securepollglobal
  - small
  - wikidataclient
  - wikipedia-english
