# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Arabic Wikibooks.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikibooks
  - categories-rdf
  - commonsuploads
  - medium
  # To be removed by end of 2020
  - mobilemainpagelegacy
  - nowikidatadescriptiontaglines
  - rtl
  - s3
  - securepollglobal
  - visualeditor-nondefault
  - wikidataclient
