# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the undefined.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - all
  - commonsuploads
  - s3
  - small
  - wikidataclient
  - wikipedia-english
