# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Central Bikol Wikiquote.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikiquote
  - commonsuploads
  - s5
  - small
  - visualeditor-nondefault
  - wikidataclient
