# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Bhojpuri Wiktionary.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wiktionary
  - all
  - closed
  - group0
  - nowikidatadescriptiontaglines
  - s3
  - securepollglobal
  - small
  - visualeditor-nondefault
  - wikidataclient
