# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Catalan Wikipedia.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - all-labs
  - categories-rdf
  - cirrussearch-big-indices
  - flow-labs
  - flow
  - gettingstarted-with-category-suggestions
  - group1-wikipedia
  - large
  # To be removed by end of 2020
  - mobilemainpagelegacy
  - s7
  - securepollglobal
  - wikidataclient
