# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Catalan Wikinews.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikinews
  - all
  - categories-rdf
  - flaggedrevs
  - medium
  - mobilemainpagelegacy
  - nowikidatadescriptiontaglines
  - s3
  - securepollglobal
  - visualeditor-nondefault
  - wikidataclient
