# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the shared trait configuration file for all wikis which have large indices
# in CirrusSearch and so need special handling.
# All settings here apply to wikis with this trait, unless over-ridden.

wikiTag: cirrussearch-big-indices
