# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the English Wikivoyage.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikivoyage
  - all-labs
  - all
  - categories-rdf
  - cirrussearch-big-indices
  - medium
  - pageassessments
  - s5
  - securepollglobal
  - wikidataclient
