# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the English Wikisource.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikisource
  - all-labs
  - categories-rdf
  - cirrussearch-big-indices
  - large
  - mobilemainpagelegacy
  - nowikidatadescriptiontaglines
  - s3
  - securepollglobal
  - visualeditor-nondefault
  - wikidataclient
