# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Esperanto Wikivoyage.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikivoyage
  - categories-rdf
  - small
  - s5
  - securepollglobal
  - wikidataclient
  - commonsuploads
