# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Spanish Wikiversity.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikiversity
  - all
  - categories-rdf
  - medium
  - nowikidatadescriptiontaglines
  - s3
  - securepollglobal
  - visualeditor-nondefault
  - wikidataclient
