# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Spanish Wikipedia.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - all-labs
  - all
  - categories-rdf
  - cirrussearch-big-indices
  - closed-labs
  - gettingstarted-with-category-suggestions
  - large
  - pp_stage1
  - s7
  - securepollglobal
  - top6-wikipedia
  - wikidataclient
  - wikipedia-english
