# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Persian Wikipedia.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - all-labs
  - categories-rdf
  - cirrussearch-big-indices
  - desktop-improvements
  - flaggedrevs
  - flow-labs
  - flow
  - gettingstarted-with-category-suggestions
  - growthexperiments
  - large
  - rtl
  - s7
  - securepollglobal
  - wikidataclient
