# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the shared trait configuration file for all wikis on the Beta Cluster which
# have the StructuredDiscussions feature enabled.
# All settings here apply to wikis with this trait, unless over-ridden.

# FIXME: This really shouldn't exist

wikiTag: flow-labs
