# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the shared trait configuration file for all wikis which have the StructuredDiscussions
# feature enabled on their Beta Cluster version but not in production.
# All settings here apply to wikis with this trait, unless over-ridden.

# FIXME: This really shouldn't exist

wikiTag: flow_only_labs
