# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the French Wikipedia.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - all
  - categories-rdf
  - cirrussearch-big-indices
  - flow
  - large
  - mobilemainpagelegacy
  - pp_stage1
  - s6
  - securepollglobal
  - top6-wikipedia
  - wikidataclient
  - wikipedia-e-acute
