# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the French Wikiversity.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikiversity
  - categories-rdf
  - cirrussearch-big-indices
  - commonsuploads
  - flow
  - medium
  - nowikidatadescriptiontaglines
  - s3
  - securepollglobal
  - wikidataclient
