# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the French Wiktionary.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wiktionary
  - categories-rdf
  - cirrussearch-big-indices
  - commonsuploads
  - flow
  - large
  - nowikidatadescriptiontaglines
  - s7
  - securepollglobal
  - wikidataclient
