# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the French Wikiquote.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikiquote
  - categories-rdf
  - commonsuploads
  - flow
  - medium
  - s3
  - securepollglobal
  - visualeditor-nondefault
  - wikidataclient
  - desktop-improvements
