# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the French Wikinews.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikinews
  - categories-rdf
  - cirrussearch-big-indices
  - flaggedrevs
  - medium
  - mobilemainpagelegacy
  - nowikidatadescriptiontaglines
  - s3
  - securepollglobal
  - wikidataclient
