# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Gilaki Wikipedia.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - categories-rdf
  - commonsuploads
  - medium
  - pp_stage1
  - rtl
  - s3
  - securepollglobal
  - wikidataclient
  - wikipedia-english
