# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Galician Wikibooks.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikibooks
  - categories-rdf
  - commonsuploads
  - mobilemainpagelegacy
  - nowikidatadescriptiontaglines
  - s3
  - securepollglobal
  - small
  - visualeditor-nondefault
  - wikidataclient
