# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Galician Wikiquote.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikiquote
  - all
  - categories-rdf
  - commonsuploads
  - mobilemainpagelegacy
  - s3
  - securepollglobal
  - small
  - visualeditor-nondefault
  - wikidataclient
