# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Wikimedia Foundation Grants Discussion.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
