# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Hebrew Wikisource.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikisource
  - all
  - categories-rdf
  - cirrussearch-big-indices
  - flaggedrevs
  - medium
  - nowikidatadescriptiontaglines
  - rtl
  - s3
  - securepollglobal
  - visualeditor-nondefault
  - wikidataclient
