# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Hebrew Wikipedia.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - all-labs
  - categories-rdf
  - cirrussearch-big-indices
  - flow-labs
  - flow
  - group1-wikipedia
  - large
  - pp_stage0
  - rtl
  - s7
  - securepollglobal
  - wikidataclient
  - wikipedia-english
