# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Hindi Wikipedia.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - all-labs
  - categories-rdf
  - cirrussearch-big-indices
  - flaggedrevs
  - medium
  - mobilemainpagelegacy
  - pp_stage1
  - s3
  - securepollglobal
  - wikidataclient
