# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Hindi Wikimedians.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikimedia
  - all
  - categories-rdf
  - fishbowl
  - s3
  - small
