# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Hungarian Wikipedia.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - all
  - categories-rdf
  - cirrussearch-big-indices
  - flaggedrevs
  - large
  - pp_stage0
  - s7
  - securepollglobal
  - wikidataclient
  - wikipedia-e-acute
