# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Internal.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - special
  - closed
  - nowikidatadescriptiontaglines
  - private
  - s3
  - securepollglobal
  - small
