# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Ido Wikipedia.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - categories-rdf
  - commonsuploads
  - medium
  # To be removed by end of 2020
  - mobilemainpagelegacy
  - s3
  - securepollglobal
  - wikidataclient
