# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Icelandic Wiktionary.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wiktionary
  - categories-rdf
  - commonsuploads
  - flaggedrevs
  - medium
  # To be removed by end of 2020
  - mobilemainpagelegacy
  - nowikidatadescriptiontaglines
  - s3
  - securepollglobal
  - visualeditor-nondefault
  - wikidataclient
