# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Italian Wikivoyage.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikivoyage
  - categories-rdf
  - commonsuploads
  - medium
  - s3
  - securepollglobal
  - wikidataclient
