# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Korean Wikipedia.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - all-labs
  - categories-rdf
  - cirrussearch-big-indices
  - commonsuploads
  - growthexperiments
  - large
  - mobilemainpagelegacy
  - pp_stage1
  - s7
  - securepollglobal
  - wikidataclient
