# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Kashmiri Wiktionary.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wiktionary
  - all
  - categories-rdf
  - commonsuploads
  - nowikidatadescriptiontaglines
  - rtl
  - s3
  - securepollglobal
  - small
  - visualeditor-nondefault
  - wikidataclient
