# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Limburgish Wikinews.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikinews
  - commonsuploads
  - nowikidatadescriptiontaglines
  - s3
  - small
  - wikidataclient
