# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the MediaWiki.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - special
  - categories-rdf
  - cirrussearch-big-indices
  - commonsuploads
  - flow
  - group0
  - medium
  - nowikidatadescriptiontaglines
  - s3
  - securepollglobal
  - wikidataclient
