# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Meta-Wiki.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - special
  - all-labs
  - categories-rdf
  - cirrussearch-big-indices
  - commonsuploads
  - large
  - nowikidatadescriptiontaglines
  - s7
  - securepollglobal
  - visualeditor-nondefault
  - wikidataclient
