# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Malagasy Wiktionary.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wiktionary
  - all
  - categories-rdf
  - cirrussearch-big-indices
  - commonsuploads
  - large
  - nowikidatadescriptiontaglines
  - s5
  - securepollglobal
  - visualeditor-nondefault
  - wikidataclient
