# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the shared trait configuration file for all wikis which should not display
# tag lines from Wikidata.
# All settings here apply to wikis with this trait, unless over-ridden.

wikiTag: nowikidatadescriptiontaglines
