# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Polish Wikipedia.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - all
  - categories-rdf
  - cirrussearch-big-indices
  - flaggedrevs
  - flow
  - large
  - mobilemainpagelegacy
  - pp_stage1
  - s2
  - securepollglobal
  - wikidataclient
  - wikipedia-english
