# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Piedmontese Wikisource.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikisource
  - all
  - commonsuploads
  - nowikidatadescriptiontaglines
  - s3
  - securepollglobal
  - small
  - wikidataclient
