# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Russian Wikipedia.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - all-labs
  - categories-rdf
  - cirrussearch-big-indices
  - commonsuploads
  - flaggedrevs
  - flow-labs
  - flow
  - gettingstarted-with-category-suggestions
  - large
  - s6
  - securepollglobal
  - top6-wikipedia
  - wikidataclient
  - wikipedia-cyrillic
