# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Shawiya Wiktionary.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wiktionary
  - commonsuploads
  - nowikidatadescriptiontaglines
  - s3
  - small
  - wikidataclient
