# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Wikispecies.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - special
  - all
  - categories-rdf
  - cirrussearch-big-indices
  - flow
  - large
  - mobilemainpagelegacy
  - nowikidatadescriptiontaglines
  - s3
  - securepollglobal
  - visualeditor-nondefault
  - wikidataclient
