# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Swedish Wikipedia.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - all-labs
  - categories-rdf
  - cirrussearch-big-indices
  - flow-labs
  - flow
  - growthexperiments
  - mobile-anon-talk # T253985
  - large
  - s2
  - securepollglobal
  - wikidataclient
