# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Wikipedia 10.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - closed
  - group0
  - nowikidatadescriptiontaglines
  - s3
  - securepollglobal
  - small
  - visualeditor-nondefault
  - wikipedia-english
