# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Test Wikipedia.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - all-labs
  - categories-rdf
  - flow-labs
  - flow
  - group0
  - growthexperiments
  - medium
  - nowikidatadescriptiontaglines
  - pageassessments
  - s3
  - securepollglobal
  - testwikis
  - wikidataclient-test
  - wikidataclient
  - wikipedia
