# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Wikidata Test Wiki.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - special
  - categories-rdf
  - group0
  - medium
  - nowikidatadescriptiontaglines
  - s3
  - securepollglobal
  - testwikis
  - wikibaserepo
  - wikidata
  - wikidataclient-test
