# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Test2 Wikipedia.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - categories-rdf
  - flaggedrevs
  - flow
  - group1-wikipedia
  - medium
  - nowikidatadescriptiontaglines
  - pp_stage1
  - s3
  - securepollglobal
  - wikidataclient-test
  - wikidataclient
  - wikipedia
