# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Tongan Wikipedia.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - categories-rdf
  - commonsuploads
  - s3
  - securepollglobal
  - small
  - wikidataclient
  - growthexperiments
  - desktop-improvements
