# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Wikipedia Seediq..
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikipedia
  - s5
  - securepollglobal
  - commonsuploads
  - wikidataclient
  - small
  - growthexperiments
