# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Wikimedia Vote Wiki.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - special
  - categories-rdf
  - fishbowl
  - nonbetafeatures
  - lockeddown
  - nonecho
  - nowikidatadescriptiontaglines
  - s3
  - securepollglobal
  - small
  - visualeditor-nondefault
