# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Wikidata.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - special
  - all-labs
  - all
  - categories-rdf
  - cirrussearch-big-indices
  - flow-labs
  - flow
  - large
  - nowikidatadescriptiontaglines
  - s8
  - securepollglobal
  - visualeditor-nondefault
  - wikibaserepo
  - wikidata
  - wikidataclient
