# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the shared configuration file for settings specific to all Wikinewses.
# All settings here apply to every Wikinews, unless over-ridden.

inheritsFrom: base
