# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the shared configuration file for settings specific to all Wikipedias.
# All settings here apply to every Wikipedia, unless over-ridden.

inheritsFrom: base

wikiTag: wikipedia


wmgSiteLogo1x: '/static/images/project-logos/enwiki.png'
wmgSiteLogoWordmark:
  - src: '/static/images/mobile/copyright/wikipedia-wordmark-en.svg'
  - width: 116
  - height: 18
