# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the shared configuration file for settings specific to all Wikipedias.
# All settings here apply to every Wikipedia, unless over-ridden.

inheritsFrom: base

wikiTag: wikipedia


wgLogos:
  - 1x: '/static/images/project-logos/enwiki.png'
