# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the shared configuration file for settings specific to all Wikimanias.
# All settings here apply to every Wikimania, unless over-ridden.

inheritsFrom: base

wikiTag: wikimania
