# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the shared configuration file for settings specific to all Wikiversities.
# All settings here apply to every Wikiversity, unless over-ridden.

inheritsFrom: base

wikiTag: wikiversity
