# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the shared configuration file for settings specific to all Wiktionaries.
# All settings here apply to every Wiktionary, unless over-ridden.

inheritsFrom: base
