# WARNING: This file is publicly viewable on the Web. Do not put private data here.
# This is the configuration file for settings specific to the Chinese Wikivoyage.
# See the inheritance tree to find where most settings are defined.

inheritsFrom:
  - wikivoyage
  - all-labs
  - categories-rdf
  - medium
  - s3
  - securepollglobal
  - visualeditor-nondefault
  - wikidataclient
